apiVersion: v1
kind: Service
metadata:
  name: serverstatus-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: serverstatus
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085